stages:
  - registry
  - test

build:
  image: docker:latest
  stage: registry
  services:
      - docker:dind
  script:
    - sh build.sh

test:
  image: registry.atech.com.br/cucumber-runner
  stage: test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - test/bundle/
  variables:
    BUNDLE_APP_CONFIG: test/bundle
  before_script:
    - cd test/
    - gem install bundler
    - bundle install
    - ls -la
  script:
    cucumber