stages:
  - registry
  - test

variables:
  image_name: cucumber-runner
  registry_server: registry.atech.com.br
  fullname: ${registry_server}/${image_name}

services:
  - docker:dind

build-2.3:
  image: docker:latest
  stage: registry
  variables:
    runner_version: "2.3"
  script:
    - docker build -t ${image_name} -f Dockerfile-${runner_version} .
    - docker tag ${image_name} ${fullname}:${runner_version}
    - docker tag ${image_name} ${fullname}:${runner_version}-${CI_COMMIT_SHA}
    - docker push ${fullname}:${runner_version}
    - docker push ${fullname}:${runner_version}-${CI_COMMIT_SHA}

build-2.4:
  image: docker:latest
  stage: registry
  variables:
    runner_version: "2.4"
  script:
    - docker build -t ${image_name} -f Dockerfile-${runner_version} .
    - docker tag ${image_name} ${fullname}:${runner_version}
    - docker tag ${image_name} ${fullname}:${runner_version}-${CI_COMMIT_SHA}
    - docker tag ${image_name} ${fullname}:latest
    - docker push ${fullname}:${runner_version}
    - docker push ${fullname}:${runner_version}-${CI_COMMIT_SHA}
    - docker push ${fullname}:latest

build-2.4-oracle:
  image: docker:latest
  stage: registry
  variables:
    runner_version: "2.4-oracle"
  before_script:
    - echo 'Commit'
    - echo ${CI_COMMIT_SHA}
  script:
    - docker build -t ${image_name} -f Dockerfile-${runner_version}-oracle .
    - docker tag ${image_name} ${fullname}:${runner_version}-oracle
    - docker tag ${image_name} ${fullname}:${runner_version}-${CI_COMMIT_SHA}
    - docker push ${fullname}:${runner_version}-oracle
    - docker push ${fullname}:${runner_version}-${CI_COMMIT_SHA}
