stages:
  - registry
  - test

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - /usr/local/bundle/
    - /usr/local/lib/ruby/gems/

build:
  image: docker:latest
  stage: registry
  services:
      - docker:dind
  script:
    - sh build.sh

test:
  image: registry.atech.com.br/cucumber-runner
  stage: test
  before_script:
    - cd test/
    - gem install bundler
    - bundle install
  script:
    cucumber