stages:
  - registry
  - test

build:
  image: docker:latest
  stage: registry
  services:
      - docker:dind
  variables:
    image_name: cucumber-runner
    registry_server: registry.atech.com.br
    fullname: ${registry_server}/${image_name}
  before_script:
    - echo 'Commit'
    - echo ${CI_COMMIT_SHA}
  script:
    - docker build -t ${image_name} .
    - docker tag ${image_name} ${fullname}:latest # tag latest version
    - docker tag ${image_name} ${fullname}:${CI_COMMIT_SHA} # tag current version
    - docker push ${fullname}:latest
    - docker push ${fullname}:${CI_COMMIT_SHA}

test:
  image: registry.atech.com.br/cucumber-runner:${CI_COMMIT_SHA}
  stage: test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - test/vendor/
  before_script:
    - cd test/
    - gem install bundler
    - bundle install --path vendor/bundle
  script:
    cucumber