stages:
  - registry
  - test

build-push:
  image: docker:latest
  stage: registry
  services:
    - docker:dind
  script:
    - sh registry.sh

test:
  image: registry.atech.com.br/cucumber
  stage: test
  before_script:
    - cd test/
    - gem install bundler
    - bundle install
  script:
    cucumber