stages:
  - registry
  - test

build-push:
  image: docker:latest
  stage: registry
  services:
    - docker:dind
  script:
    - sh build.sh
  - cache:
      key: "$CI_BUILD_REF"
      untracked: true

test:
  image: registry.atech.com.br/cucumber-runner
  stage: test
  before_script:
    - cd test/
    - gem install bundler
    - bundle install
  script:
    cucumber