FROM ruby:2.4

USER root

WORKDIR /opt

# chrome driver
RUN apt-get update > /dev/null && apt-get install -y unzip chromedriver libxi6 libgconf-2-4
RUN wget -q http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip -P /home/ && \
    unzip /home/chromedriver_linux64.zip -d /usr/local/share/ && \
    ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver && \
    ln -s /usr/local/share/chromedriver /usr/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver

# startup
COPY assets/cucumber-entrypoint.sh /opt/cucumber-entrypoint.sh

RUN useradd -ms /bin/bash -d /cucumber/ cucumber

USER cucumber

RUN gem install bundler cucumber

WORKDIR /cucumber

ENTRYPOINT [ "/opt/cucumber-entrypoint.sh" ]
